### ISSUE TITLE
Update of NHibernate 5

### ISSUE THREAD

**Issue by EnemyArea** [nhibernate/NHibernate.Spatial#85] opened 2017-10-10 10:54 UTC
Hey ppl !
When we can expect a compatible version with Nhibernate 5 support?

**Comment by nickalbrecht** [comment] 2017-10-10 20:14
I grabbed the source to NHibernate.Spatial and tried upgraded its NHibernate reference to 5.0. Didn't take too much to do. It's worth noting that I'm not involved with the NHibernate.Spatial project, I'm just testing the bare minimum to get the project to compile and run in my scenario with a [Works on My Machine](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/) level of confidence.

- Updated some method signatures due to changes in NHibernate. Specifically some methods now require `ISessionImplementor`, and some no longer need `IDictionary<string,IFilter>`.
- Change some types from `IDataReader` to `DbDataReader`, `IDbCommand` to `DbCommand` as needed to comply with methods being overridden
- Bumped target framework from 4.0 Client to 4.6.1 (NHibernate requires 4.6.1, and client profile is no longer available)
- Cleaned up some warning due to obsolete calls to `ReflectionHelper` to instead use `Util.ReflectHelper`

I bumped the version in SharedAssemblyInfo to 5.0.0 and built the packages, tried them in my internal app and everything appears to work fine. I wasn't able to run the tests locally since they are setup with appveyor. But It doesn't seem like upgrading and publishing a 5.0 version of the spatial assemblies would take long for the project authors?

**Comment by fredericDelaporte** [comment] 2017-10-18 09:21
Well, maybe can you issue a PR for that. (I am not involved in Spatial.)

**Comment by peetw** [comment] 2017-10-18 09:37
Yup, if someone can submit a PR, we'll review it and get it merged :)

**Comment by robertovaldesperez** [comment] 2017-10-18 10:48
Is it possible to have it available in nuget?

**Comment by peetw** [comment] 2017-10-18 11:03
Once someone has submitted a PR and it has been reviewed, we should be able to release an updated version to NuGet @andrerav @suryapratap

**Comment by andrerav** [comment] 2017-10-18 13:55
Can definitely confirm that a NuGet pre-release package will be available fairly quickly when the pull request arrives. @nickalbrecht Any chance you could wrap up your changes and submit a PR? We have some build and testing facilities set up that will run the unit tests. Not sure about the AppVeyor environment (is it still up @peetw?), but my old TeamCity instance is still running and will build/test pull requests automatically.

**Comment by peetw** [comment] 2017-10-18 14:29
@andrerav I created a [project](https://ci.appveyor.com/project/peetw/nhibernate-spatial) on AppVeyor for NHibernate.Spatial, but I don't have admin privileges for this project (only collab), so either you or @suryapratap will have to create an "official" project on AppVeyor to get it fully hooked up and integrated (see #83).

**Comment by nickalbrecht** [comment] 2017-10-25 20:34
I haven't had the time yet to look back into this. If no one has gotten a PR up before I have some free time to do this, I'll see what I can do.

**Closed** 2017-11-12 23:41 UTC

**Comment by EnemyArea** [comment] 2017-11-14 09:30
thank you so much ppl :D

**Comment by peetw** [comment] 2017-11-14 11:05
@andrerav thanks for reviewing and getting the NuGet packages sorted :) What needs to happen (testing, development, etc) to get the NuGet packages to full release status, rather than pre-release?

**Comment by andrerav** [comment] 2017-11-14 13:21
@peetw A few days should be enough, and I'll push new packages. By the way, I have upgraded you to admin on this repository. Can you give me access to the appveyor project as well?  My username is the same as here on Github, andrerav.

**Comment by peetw** [comment] 2017-11-14 13:30
Great, thanks :) Unfortunately I don't have access to the "official" AppVeyor project - @fredericDelaporte can you add the NHibernate.Spatial team to the project?

**Comment by fredericDelaporte** [comment] 2017-11-14 17:53
I have added the [core](https://github.com/orgs/nhibernate/teams/core), [spatial](https://github.com/orgs/nhibernate/teams/nhibernate-spatial) and [caches](https://github.com/orgs/nhibernate/teams/nhibernate-caches) teams to AppVeyor administrator role. It does not seem I can add them to only one project, so you will have access to the caches project too on AppVeyor.
@peetw does not seem to belong to any of those teams, so it is likely he will still not have access to AppVeyor.

**Comment by peetw** [comment] 2017-11-15 11:54
@fredericDelaporte thanks! How do I go about getting added to the NHibernate-Spatial team?

**Comment by andrerav** [comment] 2017-11-15 12:10
@peetw I think you need to be a member of the NHibernate organization first:

![image](https://user-images.githubusercontent.com/3635018/32835410-4854be68-ca06-11e7-81c9-09b9e6c2c3e2.png)

@fredericDelaporte Can you add @peetw to the NHibernate organization?

**Comment by fredericDelaporte** [comment] 2017-11-15 15:59
Done.

**Comment by andrerav** [comment] 2017-11-15 20:40
@peetw I have added you to the team, can you confirm that you have gained elevated privileges?

**Comment by peetw** [comment] 2017-11-15 20:58
@fredericDelaporte @andrerav thank you both, everything seems to be working as intended :) It's a little bit weird on AppVeyor when I log in via GitHub in that I now have two "accounts" (peetw and nhibernate), but that's no problem.
