### ISSUE TITLE
in PostGisGeometryType throws Exception when PostGisReader instance creating without coordinate factory

### ISSUE THREAD

**Issue by megafetis** [nhibernate/NHibernate.Spatial#108] opened 2019-09-06 07:06 UTC
Error
```
protected override IGeometry ToGeometry(object value)
        {
            var bytes = value as byte[];
            if (bytes == null)
            {
                return null;
            }

            PostGisReader reader = new PostGisReader();
            IGeometry geometry = reader.Read(bytes);
            this.SetDefaultSRID(geometry);
            return geometry;
        }
```
Success:
```
protected override IGeometry ToGeometry(object value)
        {
            var bytes = value as byte[];
            if (bytes == null)
            {
                return null;
            }
            var factory = new GeometryFactory(new PrecisionModel(), 4326);
            PostGisReader reader = new PostGisReader(factory);
            IGeometry geometry = reader.Read(bytes);
            this.SetDefaultSRID(geometry);
            return geometry;
        }

**Comment by megafetis** [comment] 2019-09-06 07:12
version of NetTopologySuite is 1.15.3.

in NetTopologySuite 2.0 may be other errors

**Comment by peetw** [comment] 2019-09-18 12:08
@megafetis what is the exact error/exception you are getting? Do you have an example we can use to reproduce?

**Comment by peetw** [comment] 2020-10-25 10:26
Closing as unable to reproduce

**Closed by peetw** 2020-10-25 10:26 UTC
